version: "3"
services:
  proxy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - proxy

  web-client:
    build:
      context: ./js-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
      - proxy
    tty: true